// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: announcement.proto

package ampPluginAdapter.protobuf.Api ;

public final class AnnouncementOuterClass {
  private AnnouncementOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AnnouncementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PluginAdapter.Api.Announcement)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The adapter name uniquely identifies this adapter. Only one adapter is
     * allowed to connect with this name at a time.
     * It's useful to use this format: interface&#64;location. For example, if the
     * adapter is connected to the PRL42 System Under Test running at company Comp
     * and provides access to its SNMP interface, then the name would be
     * snmp&#64;prl42-comp.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     * The adapter name uniquely identifies this adapter. Only one adapter is
     * allowed to connect with this name at a time.
     * It's useful to use this format: interface&#64;location. For example, if the
     * adapter is connected to the PRL42 System Under Test running at company Comp
     * and provides access to its SNMP interface, then the name would be
     * snmp&#64;prl42-comp.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * Default configuration. All values should be set to their default values.
     * </pre>
     *
     * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
     */
    boolean hasConfiguration();
    /**
     * <pre>
     * Default configuration. All values should be set to their default values.
     * </pre>
     *
     * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
     */
    PluginAdapter.Api.ConfigurationOuterClass.Configuration getConfiguration();
    /**
     * <pre>
     * Default configuration. All values should be set to their default values.
     * </pre>
     *
     * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
     */
    PluginAdapter.Api.ConfigurationOuterClass.ConfigurationOrBuilder getConfigurationOrBuilder();

    /**
     * <pre>
     * Labels that this adapter supports.
     * </pre>
     *
     * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
     */
    java.util.List<PluginAdapter.Api.LabelOuterClass.Label> 
        getLabelsList();
    /**
     * <pre>
     * Labels that this adapter supports.
     * </pre>
     *
     * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
     */
    PluginAdapter.Api.LabelOuterClass.Label getLabels(int index);
    /**
     * <pre>
     * Labels that this adapter supports.
     * </pre>
     *
     * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
     */
    int getLabelsCount();
    /**
     * <pre>
     * Labels that this adapter supports.
     * </pre>
     *
     * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
     */
    java.util.List<? extends PluginAdapter.Api.LabelOuterClass.LabelOrBuilder> 
        getLabelsOrBuilderList();
    /**
     * <pre>
     * Labels that this adapter supports.
     * </pre>
     *
     * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
     */
    PluginAdapter.Api.LabelOuterClass.LabelOrBuilder getLabelsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * Announcement of an adapter when it plugs in.
   * </pre>
   *
   * Protobuf type {@code PluginAdapter.Api.Announcement}
   */
  public  static final class Announcement extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PluginAdapter.Api.Announcement)
      AnnouncementOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Announcement.newBuilder() to construct.
    private Announcement(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Announcement() {
      name_ = "";
      labels_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Announcement(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              PluginAdapter.Api.ConfigurationOuterClass.Configuration.Builder subBuilder = null;
              if (configuration_ != null) {
                subBuilder = configuration_.toBuilder();
              }
              configuration_ = input.readMessage(PluginAdapter.Api.ConfigurationOuterClass.Configuration.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(configuration_);
                configuration_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                labels_ = new java.util.ArrayList<PluginAdapter.Api.LabelOuterClass.Label>();
                mutable_bitField0_ |= 0x00000004;
              }
              labels_.add(
                  input.readMessage(PluginAdapter.Api.LabelOuterClass.Label.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          labels_ = java.util.Collections.unmodifiableList(labels_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PluginAdapter.Api.AnnouncementOuterClass.internal_static_PluginAdapter_Api_Announcement_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PluginAdapter.Api.AnnouncementOuterClass.internal_static_PluginAdapter_Api_Announcement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PluginAdapter.Api.AnnouncementOuterClass.Announcement.class, PluginAdapter.Api.AnnouncementOuterClass.Announcement.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * The adapter name uniquely identifies this adapter. Only one adapter is
     * allowed to connect with this name at a time.
     * It's useful to use this format: interface&#64;location. For example, if the
     * adapter is connected to the PRL42 System Under Test running at company Comp
     * and provides access to its SNMP interface, then the name would be
     * snmp&#64;prl42-comp.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The adapter name uniquely identifies this adapter. Only one adapter is
     * allowed to connect with this name at a time.
     * It's useful to use this format: interface&#64;location. For example, if the
     * adapter is connected to the PRL42 System Under Test running at company Comp
     * and provides access to its SNMP interface, then the name would be
     * snmp&#64;prl42-comp.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONFIGURATION_FIELD_NUMBER = 2;
    private PluginAdapter.Api.ConfigurationOuterClass.Configuration configuration_;
    /**
     * <pre>
     * Default configuration. All values should be set to their default values.
     * </pre>
     *
     * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
     */
    public boolean hasConfiguration() {
      return configuration_ != null;
    }
    /**
     * <pre>
     * Default configuration. All values should be set to their default values.
     * </pre>
     *
     * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
     */
    public PluginAdapter.Api.ConfigurationOuterClass.Configuration getConfiguration() {
      return configuration_ == null ? PluginAdapter.Api.ConfigurationOuterClass.Configuration.getDefaultInstance() : configuration_;
    }
    /**
     * <pre>
     * Default configuration. All values should be set to their default values.
     * </pre>
     *
     * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
     */
    public PluginAdapter.Api.ConfigurationOuterClass.ConfigurationOrBuilder getConfigurationOrBuilder() {
      return getConfiguration();
    }

    public static final int LABELS_FIELD_NUMBER = 3;
    private java.util.List<PluginAdapter.Api.LabelOuterClass.Label> labels_;
    /**
     * <pre>
     * Labels that this adapter supports.
     * </pre>
     *
     * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
     */
    public java.util.List<PluginAdapter.Api.LabelOuterClass.Label> getLabelsList() {
      return labels_;
    }
    /**
     * <pre>
     * Labels that this adapter supports.
     * </pre>
     *
     * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
     */
    public java.util.List<? extends PluginAdapter.Api.LabelOuterClass.LabelOrBuilder> 
        getLabelsOrBuilderList() {
      return labels_;
    }
    /**
     * <pre>
     * Labels that this adapter supports.
     * </pre>
     *
     * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
     */
    public int getLabelsCount() {
      return labels_.size();
    }
    /**
     * <pre>
     * Labels that this adapter supports.
     * </pre>
     *
     * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
     */
    public PluginAdapter.Api.LabelOuterClass.Label getLabels(int index) {
      return labels_.get(index);
    }
    /**
     * <pre>
     * Labels that this adapter supports.
     * </pre>
     *
     * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
     */
    public PluginAdapter.Api.LabelOuterClass.LabelOrBuilder getLabelsOrBuilder(
        int index) {
      return labels_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (configuration_ != null) {
        output.writeMessage(2, getConfiguration());
      }
      for (int i = 0; i < labels_.size(); i++) {
        output.writeMessage(3, labels_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (configuration_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getConfiguration());
      }
      for (int i = 0; i < labels_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, labels_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PluginAdapter.Api.AnnouncementOuterClass.Announcement)) {
        return super.equals(obj);
      }
      PluginAdapter.Api.AnnouncementOuterClass.Announcement other = (PluginAdapter.Api.AnnouncementOuterClass.Announcement) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && (hasConfiguration() == other.hasConfiguration());
      if (hasConfiguration()) {
        result = result && getConfiguration()
            .equals(other.getConfiguration());
      }
      result = result && getLabelsList()
          .equals(other.getLabelsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (hasConfiguration()) {
        hash = (37 * hash) + CONFIGURATION_FIELD_NUMBER;
        hash = (53 * hash) + getConfiguration().hashCode();
      }
      if (getLabelsCount() > 0) {
        hash = (37 * hash) + LABELS_FIELD_NUMBER;
        hash = (53 * hash) + getLabelsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PluginAdapter.Api.AnnouncementOuterClass.Announcement prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Announcement of an adapter when it plugs in.
     * </pre>
     *
     * Protobuf type {@code PluginAdapter.Api.Announcement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PluginAdapter.Api.Announcement)
        PluginAdapter.Api.AnnouncementOuterClass.AnnouncementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PluginAdapter.Api.AnnouncementOuterClass.internal_static_PluginAdapter_Api_Announcement_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PluginAdapter.Api.AnnouncementOuterClass.internal_static_PluginAdapter_Api_Announcement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PluginAdapter.Api.AnnouncementOuterClass.Announcement.class, PluginAdapter.Api.AnnouncementOuterClass.Announcement.Builder.class);
      }

      // Construct using PluginAdapter.Api.AnnouncementOuterClass.Announcement.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLabelsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        if (configurationBuilder_ == null) {
          configuration_ = null;
        } else {
          configuration_ = null;
          configurationBuilder_ = null;
        }
        if (labelsBuilder_ == null) {
          labels_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          labelsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PluginAdapter.Api.AnnouncementOuterClass.internal_static_PluginAdapter_Api_Announcement_descriptor;
      }

      @java.lang.Override
      public PluginAdapter.Api.AnnouncementOuterClass.Announcement getDefaultInstanceForType() {
        return PluginAdapter.Api.AnnouncementOuterClass.Announcement.getDefaultInstance();
      }

      @java.lang.Override
      public PluginAdapter.Api.AnnouncementOuterClass.Announcement build() {
        PluginAdapter.Api.AnnouncementOuterClass.Announcement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PluginAdapter.Api.AnnouncementOuterClass.Announcement buildPartial() {
        PluginAdapter.Api.AnnouncementOuterClass.Announcement result = new PluginAdapter.Api.AnnouncementOuterClass.Announcement(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        if (configurationBuilder_ == null) {
          result.configuration_ = configuration_;
        } else {
          result.configuration_ = configurationBuilder_.build();
        }
        if (labelsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            labels_ = java.util.Collections.unmodifiableList(labels_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.labels_ = labels_;
        } else {
          result.labels_ = labelsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PluginAdapter.Api.AnnouncementOuterClass.Announcement) {
          return mergeFrom((PluginAdapter.Api.AnnouncementOuterClass.Announcement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PluginAdapter.Api.AnnouncementOuterClass.Announcement other) {
        if (other == PluginAdapter.Api.AnnouncementOuterClass.Announcement.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.hasConfiguration()) {
          mergeConfiguration(other.getConfiguration());
        }
        if (labelsBuilder_ == null) {
          if (!other.labels_.isEmpty()) {
            if (labels_.isEmpty()) {
              labels_ = other.labels_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureLabelsIsMutable();
              labels_.addAll(other.labels_);
            }
            onChanged();
          }
        } else {
          if (!other.labels_.isEmpty()) {
            if (labelsBuilder_.isEmpty()) {
              labelsBuilder_.dispose();
              labelsBuilder_ = null;
              labels_ = other.labels_;
              bitField0_ = (bitField0_ & ~0x00000004);
              labelsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLabelsFieldBuilder() : null;
            } else {
              labelsBuilder_.addAllMessages(other.labels_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PluginAdapter.Api.AnnouncementOuterClass.Announcement parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PluginAdapter.Api.AnnouncementOuterClass.Announcement) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * The adapter name uniquely identifies this adapter. Only one adapter is
       * allowed to connect with this name at a time.
       * It's useful to use this format: interface&#64;location. For example, if the
       * adapter is connected to the PRL42 System Under Test running at company Comp
       * and provides access to its SNMP interface, then the name would be
       * snmp&#64;prl42-comp.
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The adapter name uniquely identifies this adapter. Only one adapter is
       * allowed to connect with this name at a time.
       * It's useful to use this format: interface&#64;location. For example, if the
       * adapter is connected to the PRL42 System Under Test running at company Comp
       * and provides access to its SNMP interface, then the name would be
       * snmp&#64;prl42-comp.
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The adapter name uniquely identifies this adapter. Only one adapter is
       * allowed to connect with this name at a time.
       * It's useful to use this format: interface&#64;location. For example, if the
       * adapter is connected to the PRL42 System Under Test running at company Comp
       * and provides access to its SNMP interface, then the name would be
       * snmp&#64;prl42-comp.
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The adapter name uniquely identifies this adapter. Only one adapter is
       * allowed to connect with this name at a time.
       * It's useful to use this format: interface&#64;location. For example, if the
       * adapter is connected to the PRL42 System Under Test running at company Comp
       * and provides access to its SNMP interface, then the name would be
       * snmp&#64;prl42-comp.
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The adapter name uniquely identifies this adapter. Only one adapter is
       * allowed to connect with this name at a time.
       * It's useful to use this format: interface&#64;location. For example, if the
       * adapter is connected to the PRL42 System Under Test running at company Comp
       * and provides access to its SNMP interface, then the name would be
       * snmp&#64;prl42-comp.
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private PluginAdapter.Api.ConfigurationOuterClass.Configuration configuration_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          PluginAdapter.Api.ConfigurationOuterClass.Configuration, PluginAdapter.Api.ConfigurationOuterClass.Configuration.Builder, PluginAdapter.Api.ConfigurationOuterClass.ConfigurationOrBuilder> configurationBuilder_;
      /**
       * <pre>
       * Default configuration. All values should be set to their default values.
       * </pre>
       *
       * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
       */
      public boolean hasConfiguration() {
        return configurationBuilder_ != null || configuration_ != null;
      }
      /**
       * <pre>
       * Default configuration. All values should be set to their default values.
       * </pre>
       *
       * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
       */
      public PluginAdapter.Api.ConfigurationOuterClass.Configuration getConfiguration() {
        if (configurationBuilder_ == null) {
          return configuration_ == null ? PluginAdapter.Api.ConfigurationOuterClass.Configuration.getDefaultInstance() : configuration_;
        } else {
          return configurationBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Default configuration. All values should be set to their default values.
       * </pre>
       *
       * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
       */
      public Builder setConfiguration(PluginAdapter.Api.ConfigurationOuterClass.Configuration value) {
        if (configurationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          configuration_ = value;
          onChanged();
        } else {
          configurationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Default configuration. All values should be set to their default values.
       * </pre>
       *
       * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
       */
      public Builder setConfiguration(
          PluginAdapter.Api.ConfigurationOuterClass.Configuration.Builder builderForValue) {
        if (configurationBuilder_ == null) {
          configuration_ = builderForValue.build();
          onChanged();
        } else {
          configurationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Default configuration. All values should be set to their default values.
       * </pre>
       *
       * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
       */
      public Builder mergeConfiguration(PluginAdapter.Api.ConfigurationOuterClass.Configuration value) {
        if (configurationBuilder_ == null) {
          if (configuration_ != null) {
            configuration_ =
              PluginAdapter.Api.ConfigurationOuterClass.Configuration.newBuilder(configuration_).mergeFrom(value).buildPartial();
          } else {
            configuration_ = value;
          }
          onChanged();
        } else {
          configurationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Default configuration. All values should be set to their default values.
       * </pre>
       *
       * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
       */
      public Builder clearConfiguration() {
        if (configurationBuilder_ == null) {
          configuration_ = null;
          onChanged();
        } else {
          configuration_ = null;
          configurationBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Default configuration. All values should be set to their default values.
       * </pre>
       *
       * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
       */
      public PluginAdapter.Api.ConfigurationOuterClass.Configuration.Builder getConfigurationBuilder() {
        
        onChanged();
        return getConfigurationFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Default configuration. All values should be set to their default values.
       * </pre>
       *
       * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
       */
      public PluginAdapter.Api.ConfigurationOuterClass.ConfigurationOrBuilder getConfigurationOrBuilder() {
        if (configurationBuilder_ != null) {
          return configurationBuilder_.getMessageOrBuilder();
        } else {
          return configuration_ == null ?
              PluginAdapter.Api.ConfigurationOuterClass.Configuration.getDefaultInstance() : configuration_;
        }
      }
      /**
       * <pre>
       * Default configuration. All values should be set to their default values.
       * </pre>
       *
       * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          PluginAdapter.Api.ConfigurationOuterClass.Configuration, PluginAdapter.Api.ConfigurationOuterClass.Configuration.Builder, PluginAdapter.Api.ConfigurationOuterClass.ConfigurationOrBuilder> 
          getConfigurationFieldBuilder() {
        if (configurationBuilder_ == null) {
          configurationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              PluginAdapter.Api.ConfigurationOuterClass.Configuration, PluginAdapter.Api.ConfigurationOuterClass.Configuration.Builder, PluginAdapter.Api.ConfigurationOuterClass.ConfigurationOrBuilder>(
                  getConfiguration(),
                  getParentForChildren(),
                  isClean());
          configuration_ = null;
        }
        return configurationBuilder_;
      }

      private java.util.List<PluginAdapter.Api.LabelOuterClass.Label> labels_ =
        java.util.Collections.emptyList();
      private void ensureLabelsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          labels_ = new java.util.ArrayList<PluginAdapter.Api.LabelOuterClass.Label>(labels_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          PluginAdapter.Api.LabelOuterClass.Label, PluginAdapter.Api.LabelOuterClass.Label.Builder, PluginAdapter.Api.LabelOuterClass.LabelOrBuilder> labelsBuilder_;

      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public java.util.List<PluginAdapter.Api.LabelOuterClass.Label> getLabelsList() {
        if (labelsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(labels_);
        } else {
          return labelsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public int getLabelsCount() {
        if (labelsBuilder_ == null) {
          return labels_.size();
        } else {
          return labelsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public PluginAdapter.Api.LabelOuterClass.Label getLabels(int index) {
        if (labelsBuilder_ == null) {
          return labels_.get(index);
        } else {
          return labelsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public Builder setLabels(
          int index, PluginAdapter.Api.LabelOuterClass.Label value) {
        if (labelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLabelsIsMutable();
          labels_.set(index, value);
          onChanged();
        } else {
          labelsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public Builder setLabels(
          int index, PluginAdapter.Api.LabelOuterClass.Label.Builder builderForValue) {
        if (labelsBuilder_ == null) {
          ensureLabelsIsMutable();
          labels_.set(index, builderForValue.build());
          onChanged();
        } else {
          labelsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public Builder addLabels(PluginAdapter.Api.LabelOuterClass.Label value) {
        if (labelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLabelsIsMutable();
          labels_.add(value);
          onChanged();
        } else {
          labelsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public Builder addLabels(
          int index, PluginAdapter.Api.LabelOuterClass.Label value) {
        if (labelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLabelsIsMutable();
          labels_.add(index, value);
          onChanged();
        } else {
          labelsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public Builder addLabels(
          PluginAdapter.Api.LabelOuterClass.Label.Builder builderForValue) {
        if (labelsBuilder_ == null) {
          ensureLabelsIsMutable();
          labels_.add(builderForValue.build());
          onChanged();
        } else {
          labelsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public Builder addLabels(
          int index, PluginAdapter.Api.LabelOuterClass.Label.Builder builderForValue) {
        if (labelsBuilder_ == null) {
          ensureLabelsIsMutable();
          labels_.add(index, builderForValue.build());
          onChanged();
        } else {
          labelsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public Builder addAllLabels(
          java.lang.Iterable<? extends PluginAdapter.Api.LabelOuterClass.Label> values) {
        if (labelsBuilder_ == null) {
          ensureLabelsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, labels_);
          onChanged();
        } else {
          labelsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public Builder clearLabels() {
        if (labelsBuilder_ == null) {
          labels_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          labelsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public Builder removeLabels(int index) {
        if (labelsBuilder_ == null) {
          ensureLabelsIsMutable();
          labels_.remove(index);
          onChanged();
        } else {
          labelsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public PluginAdapter.Api.LabelOuterClass.Label.Builder getLabelsBuilder(
          int index) {
        return getLabelsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public PluginAdapter.Api.LabelOuterClass.LabelOrBuilder getLabelsOrBuilder(
          int index) {
        if (labelsBuilder_ == null) {
          return labels_.get(index);  } else {
          return labelsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public java.util.List<? extends PluginAdapter.Api.LabelOuterClass.LabelOrBuilder> 
           getLabelsOrBuilderList() {
        if (labelsBuilder_ != null) {
          return labelsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(labels_);
        }
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public PluginAdapter.Api.LabelOuterClass.Label.Builder addLabelsBuilder() {
        return getLabelsFieldBuilder().addBuilder(
            PluginAdapter.Api.LabelOuterClass.Label.getDefaultInstance());
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public PluginAdapter.Api.LabelOuterClass.Label.Builder addLabelsBuilder(
          int index) {
        return getLabelsFieldBuilder().addBuilder(
            index, PluginAdapter.Api.LabelOuterClass.Label.getDefaultInstance());
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public java.util.List<PluginAdapter.Api.LabelOuterClass.Label.Builder> 
           getLabelsBuilderList() {
        return getLabelsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          PluginAdapter.Api.LabelOuterClass.Label, PluginAdapter.Api.LabelOuterClass.Label.Builder, PluginAdapter.Api.LabelOuterClass.LabelOrBuilder> 
          getLabelsFieldBuilder() {
        if (labelsBuilder_ == null) {
          labelsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              PluginAdapter.Api.LabelOuterClass.Label, PluginAdapter.Api.LabelOuterClass.Label.Builder, PluginAdapter.Api.LabelOuterClass.LabelOrBuilder>(
                  labels_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          labels_ = null;
        }
        return labelsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PluginAdapter.Api.Announcement)
    }

    // @@protoc_insertion_point(class_scope:PluginAdapter.Api.Announcement)
    private static final PluginAdapter.Api.AnnouncementOuterClass.Announcement DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PluginAdapter.Api.AnnouncementOuterClass.Announcement();
    }

    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Announcement>
        PARSER = new com.google.protobuf.AbstractParser<Announcement>() {
      @java.lang.Override
      public Announcement parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Announcement(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Announcement> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Announcement> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PluginAdapter.Api.AnnouncementOuterClass.Announcement getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PluginAdapter_Api_Announcement_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PluginAdapter_Api_Announcement_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022announcement.proto\022\021PluginAdapter.Api\032" +
      "\023configuration.proto\032\013label.proto\"\177\n\014Ann" +
      "ouncement\022\014\n\004name\030\001 \001(\t\0227\n\rconfiguration" +
      "\030\002 \001(\0132 .PluginAdapter.Api.Configuration" +
      "\022(\n\006labels\030\003 \003(\0132\030.PluginAdapter.Api.Lab" +
      "elb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          PluginAdapter.Api.ConfigurationOuterClass.getDescriptor(),
          PluginAdapter.Api.LabelOuterClass.getDescriptor(),
        }, assigner);
    internal_static_PluginAdapter_Api_Announcement_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PluginAdapter_Api_Announcement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PluginAdapter_Api_Announcement_descriptor,
        new java.lang.String[] { "Name", "Configuration", "Labels", });
    PluginAdapter.Api.ConfigurationOuterClass.getDescriptor();
    PluginAdapter.Api.LabelOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
