// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: configuration.proto

package PluginAdapter.Api;

public final class ConfigurationOuterClass {
  private ConfigurationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConfigurationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PluginAdapter.Api.Configuration)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
     */
    java.util.List<PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item> 
        getItemsList();
    /**
     * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
     */
    PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item getItems(int index);
    /**
     * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
     */
    java.util.List<? extends PluginAdapter.Api.ConfigurationOuterClass.Configuration.ItemOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
     */
    PluginAdapter.Api.ConfigurationOuterClass.Configuration.ItemOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * Configurations contain a list of key-value pairs where each key identifies
   * something that can be configured and the value contains either the default
   * value (if the message comes from the adapter) or the current value (if the
   * message comes from TestManager).
   * </pre>
   *
   * Protobuf type {@code PluginAdapter.Api.Configuration}
   */
  public  static final class Configuration extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PluginAdapter.Api.Configuration)
      ConfigurationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Configuration.newBuilder() to construct.
    private Configuration(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Configuration() {
      items_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Configuration(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                items_ = new java.util.ArrayList<PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item>();
                mutable_bitField0_ |= 0x00000001;
              }
              items_.add(
                  input.readMessage(PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PluginAdapter.Api.ConfigurationOuterClass.internal_static_PluginAdapter_Api_Configuration_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PluginAdapter.Api.ConfigurationOuterClass.internal_static_PluginAdapter_Api_Configuration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PluginAdapter.Api.ConfigurationOuterClass.Configuration.class, PluginAdapter.Api.ConfigurationOuterClass.Configuration.Builder.class);
    }

    public interface ItemOrBuilder extends
        // @@protoc_insertion_point(interface_extends:PluginAdapter.Api.Configuration.Item)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       * Should match /^[a-zA-Z0-9]+[a-zA-Z0-9_]*$/
       * </pre>
       *
       * <code>string key = 1;</code>
       */
      java.lang.String getKey();
      /**
       * <pre>
       * Should match /^[a-zA-Z0-9]+[a-zA-Z0-9_]*$/
       * </pre>
       *
       * <code>string key = 1;</code>
       */
      com.google.protobuf.ByteString
          getKeyBytes();

      /**
       * <code>string description = 2;</code>
       */
      java.lang.String getDescription();
      /**
       * <code>string description = 2;</code>
       */
      com.google.protobuf.ByteString
          getDescriptionBytes();

      /**
       * <code>string string = 3;</code>
       */
      java.lang.String getString();
      /**
       * <code>string string = 3;</code>
       */
      com.google.protobuf.ByteString
          getStringBytes();

      /**
       * <code>int64 integer = 4;</code>
       */
      long getInteger();

      /**
       * <code>float float = 5;</code>
       */
      float getFloat();

      /**
       * <code>bool boolean = 6;</code>
       */
      boolean getBoolean();

      public PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item.TypeCase getTypeCase();
    }
    /**
     * Protobuf type {@code PluginAdapter.Api.Configuration.Item}
     */
    public  static final class Item extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:PluginAdapter.Api.Configuration.Item)
        ItemOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Item.newBuilder() to construct.
      private Item(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Item() {
        key_ = "";
        description_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Item(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                key_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                description_ = s;
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();
                typeCase_ = 3;
                type_ = s;
                break;
              }
              case 32: {
                typeCase_ = 4;
                type_ = input.readInt64();
                break;
              }
              case 45: {
                typeCase_ = 5;
                type_ = input.readFloat();
                break;
              }
              case 48: {
                typeCase_ = 6;
                type_ = input.readBool();
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PluginAdapter.Api.ConfigurationOuterClass.internal_static_PluginAdapter_Api_Configuration_Item_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PluginAdapter.Api.ConfigurationOuterClass.internal_static_PluginAdapter_Api_Configuration_Item_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item.class, PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item.Builder.class);
      }

      private int typeCase_ = 0;
      private java.lang.Object type_;
      public enum TypeCase
          implements com.google.protobuf.Internal.EnumLite {
        STRING(3),
        INTEGER(4),
        FLOAT(5),
        BOOLEAN(6),
        TYPE_NOT_SET(0);
        private final int value;
        private TypeCase(int value) {
          this.value = value;
        }
        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static TypeCase valueOf(int value) {
          return forNumber(value);
        }

        public static TypeCase forNumber(int value) {
          switch (value) {
            case 3: return STRING;
            case 4: return INTEGER;
            case 5: return FLOAT;
            case 6: return BOOLEAN;
            case 0: return TYPE_NOT_SET;
            default: return null;
          }
        }
        public int getNumber() {
          return this.value;
        }
      };

      public TypeCase
      getTypeCase() {
        return TypeCase.forNumber(
            typeCase_);
      }

      public static final int KEY_FIELD_NUMBER = 1;
      private volatile java.lang.Object key_;
      /**
       * <pre>
       * Should match /^[a-zA-Z0-9]+[a-zA-Z0-9_]*$/
       * </pre>
       *
       * <code>string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * Should match /^[a-zA-Z0-9]+[a-zA-Z0-9_]*$/
       * </pre>
       *
       * <code>string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int DESCRIPTION_FIELD_NUMBER = 2;
      private volatile java.lang.Object description_;
      /**
       * <code>string description = 2;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        }
      }
      /**
       * <code>string description = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int STRING_FIELD_NUMBER = 3;
      /**
       * <code>string string = 3;</code>
       */
      public java.lang.String getString() {
        java.lang.Object ref = "";
        if (typeCase_ == 3) {
          ref = type_;
        }
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (typeCase_ == 3) {
            type_ = s;
          }
          return s;
        }
      }
      /**
       * <code>string string = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStringBytes() {
        java.lang.Object ref = "";
        if (typeCase_ == 3) {
          ref = type_;
        }
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (typeCase_ == 3) {
            type_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int INTEGER_FIELD_NUMBER = 4;
      /**
       * <code>int64 integer = 4;</code>
       */
      public long getInteger() {
        if (typeCase_ == 4) {
          return (java.lang.Long) type_;
        }
        return 0L;
      }

      public static final int FLOAT_FIELD_NUMBER = 5;
      /**
       * <code>float float = 5;</code>
       */
      public float getFloat() {
        if (typeCase_ == 5) {
          return (java.lang.Float) type_;
        }
        return 0F;
      }

      public static final int BOOLEAN_FIELD_NUMBER = 6;
      /**
       * <code>bool boolean = 6;</code>
       */
      public boolean getBoolean() {
        if (typeCase_ == 6) {
          return (java.lang.Boolean) type_;
        }
        return false;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getKeyBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
        }
        if (!getDescriptionBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_);
        }
        if (typeCase_ == 3) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, type_);
        }
        if (typeCase_ == 4) {
          output.writeInt64(
              4, (long)((java.lang.Long) type_));
        }
        if (typeCase_ == 5) {
          output.writeFloat(
              5, (float)((java.lang.Float) type_));
        }
        if (typeCase_ == 6) {
          output.writeBool(
              6, (boolean)((java.lang.Boolean) type_));
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getKeyBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
        }
        if (!getDescriptionBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, description_);
        }
        if (typeCase_ == 3) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, type_);
        }
        if (typeCase_ == 4) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(
                4, (long)((java.lang.Long) type_));
        }
        if (typeCase_ == 5) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(
                5, (float)((java.lang.Float) type_));
        }
        if (typeCase_ == 6) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(
                6, (boolean)((java.lang.Boolean) type_));
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item)) {
          return super.equals(obj);
        }
        PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item other = (PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item) obj;

        boolean result = true;
        result = result && getKey()
            .equals(other.getKey());
        result = result && getDescription()
            .equals(other.getDescription());
        result = result && getTypeCase().equals(
            other.getTypeCase());
        if (!result) return false;
        switch (typeCase_) {
          case 3:
            result = result && getString()
                .equals(other.getString());
            break;
          case 4:
            result = result && (getInteger()
                == other.getInteger());
            break;
          case 5:
            result = result && (
                java.lang.Float.floatToIntBits(getFloat())
                == java.lang.Float.floatToIntBits(
                    other.getFloat()));
            break;
          case 6:
            result = result && (getBoolean()
                == other.getBoolean());
            break;
          case 0:
          default:
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
        hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
        hash = (53 * hash) + getDescription().hashCode();
        switch (typeCase_) {
          case 3:
            hash = (37 * hash) + STRING_FIELD_NUMBER;
            hash = (53 * hash) + getString().hashCode();
            break;
          case 4:
            hash = (37 * hash) + INTEGER_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getInteger());
            break;
          case 5:
            hash = (37 * hash) + FLOAT_FIELD_NUMBER;
            hash = (53 * hash) + java.lang.Float.floatToIntBits(
                getFloat());
            break;
          case 6:
            hash = (37 * hash) + BOOLEAN_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                getBoolean());
            break;
          case 0:
          default:
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code PluginAdapter.Api.Configuration.Item}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:PluginAdapter.Api.Configuration.Item)
          PluginAdapter.Api.ConfigurationOuterClass.Configuration.ItemOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return PluginAdapter.Api.ConfigurationOuterClass.internal_static_PluginAdapter_Api_Configuration_Item_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return PluginAdapter.Api.ConfigurationOuterClass.internal_static_PluginAdapter_Api_Configuration_Item_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item.class, PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item.Builder.class);
        }

        // Construct using PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          key_ = "";

          description_ = "";

          typeCase_ = 0;
          type_ = null;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return PluginAdapter.Api.ConfigurationOuterClass.internal_static_PluginAdapter_Api_Configuration_Item_descriptor;
        }

        @java.lang.Override
        public PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item getDefaultInstanceForType() {
          return PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item.getDefaultInstance();
        }

        @java.lang.Override
        public PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item build() {
          PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item buildPartial() {
          PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item result = new PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item(this);
          result.key_ = key_;
          result.description_ = description_;
          if (typeCase_ == 3) {
            result.type_ = type_;
          }
          if (typeCase_ == 4) {
            result.type_ = type_;
          }
          if (typeCase_ == 5) {
            result.type_ = type_;
          }
          if (typeCase_ == 6) {
            result.type_ = type_;
          }
          result.typeCase_ = typeCase_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item) {
            return mergeFrom((PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item other) {
          if (other == PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item.getDefaultInstance()) return this;
          if (!other.getKey().isEmpty()) {
            key_ = other.key_;
            onChanged();
          }
          if (!other.getDescription().isEmpty()) {
            description_ = other.description_;
            onChanged();
          }
          switch (other.getTypeCase()) {
            case STRING: {
              typeCase_ = 3;
              type_ = other.type_;
              onChanged();
              break;
            }
            case INTEGER: {
              setInteger(other.getInteger());
              break;
            }
            case FLOAT: {
              setFloat(other.getFloat());
              break;
            }
            case BOOLEAN: {
              setBoolean(other.getBoolean());
              break;
            }
            case TYPE_NOT_SET: {
              break;
            }
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int typeCase_ = 0;
        private java.lang.Object type_;
        public TypeCase
            getTypeCase() {
          return TypeCase.forNumber(
              typeCase_);
        }

        public Builder clearType() {
          typeCase_ = 0;
          type_ = null;
          onChanged();
          return this;
        }


        private java.lang.Object key_ = "";
        /**
         * <pre>
         * Should match /^[a-zA-Z0-9]+[a-zA-Z0-9_]*$/
         * </pre>
         *
         * <code>string key = 1;</code>
         */
        public java.lang.String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            key_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         * Should match /^[a-zA-Z0-9]+[a-zA-Z0-9_]*$/
         * </pre>
         *
         * <code>string key = 1;</code>
         */
        public com.google.protobuf.ByteString
            getKeyBytes() {
          java.lang.Object ref = key_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            key_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * Should match /^[a-zA-Z0-9]+[a-zA-Z0-9_]*$/
         * </pre>
         *
         * <code>string key = 1;</code>
         */
        public Builder setKey(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Should match /^[a-zA-Z0-9]+[a-zA-Z0-9_]*$/
         * </pre>
         *
         * <code>string key = 1;</code>
         */
        public Builder clearKey() {
          
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Should match /^[a-zA-Z0-9]+[a-zA-Z0-9_]*$/
         * </pre>
         *
         * <code>string key = 1;</code>
         */
        public Builder setKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          key_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object description_ = "";
        /**
         * <code>string description = 2;</code>
         */
        public java.lang.String getDescription() {
          java.lang.Object ref = description_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            description_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string description = 2;</code>
         */
        public com.google.protobuf.ByteString
            getDescriptionBytes() {
          java.lang.Object ref = description_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            description_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string description = 2;</code>
         */
        public Builder setDescription(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          description_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string description = 2;</code>
         */
        public Builder clearDescription() {
          
          description_ = getDefaultInstance().getDescription();
          onChanged();
          return this;
        }
        /**
         * <code>string description = 2;</code>
         */
        public Builder setDescriptionBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          description_ = value;
          onChanged();
          return this;
        }

        /**
         * <code>string string = 3;</code>
         */
        public java.lang.String getString() {
          java.lang.Object ref = "";
          if (typeCase_ == 3) {
            ref = type_;
          }
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (typeCase_ == 3) {
              type_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string string = 3;</code>
         */
        public com.google.protobuf.ByteString
            getStringBytes() {
          java.lang.Object ref = "";
          if (typeCase_ == 3) {
            ref = type_;
          }
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            if (typeCase_ == 3) {
              type_ = b;
            }
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string string = 3;</code>
         */
        public Builder setString(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  typeCase_ = 3;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string string = 3;</code>
         */
        public Builder clearString() {
          if (typeCase_ == 3) {
            typeCase_ = 0;
            type_ = null;
            onChanged();
          }
          return this;
        }
        /**
         * <code>string string = 3;</code>
         */
        public Builder setStringBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          typeCase_ = 3;
          type_ = value;
          onChanged();
          return this;
        }

        /**
         * <code>int64 integer = 4;</code>
         */
        public long getInteger() {
          if (typeCase_ == 4) {
            return (java.lang.Long) type_;
          }
          return 0L;
        }
        /**
         * <code>int64 integer = 4;</code>
         */
        public Builder setInteger(long value) {
          typeCase_ = 4;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 integer = 4;</code>
         */
        public Builder clearInteger() {
          if (typeCase_ == 4) {
            typeCase_ = 0;
            type_ = null;
            onChanged();
          }
          return this;
        }

        /**
         * <code>float float = 5;</code>
         */
        public float getFloat() {
          if (typeCase_ == 5) {
            return (java.lang.Float) type_;
          }
          return 0F;
        }
        /**
         * <code>float float = 5;</code>
         */
        public Builder setFloat(float value) {
          typeCase_ = 5;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>float float = 5;</code>
         */
        public Builder clearFloat() {
          if (typeCase_ == 5) {
            typeCase_ = 0;
            type_ = null;
            onChanged();
          }
          return this;
        }

        /**
         * <code>bool boolean = 6;</code>
         */
        public boolean getBoolean() {
          if (typeCase_ == 6) {
            return (java.lang.Boolean) type_;
          }
          return false;
        }
        /**
         * <code>bool boolean = 6;</code>
         */
        public Builder setBoolean(boolean value) {
          typeCase_ = 6;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>bool boolean = 6;</code>
         */
        public Builder clearBoolean() {
          if (typeCase_ == 6) {
            typeCase_ = 0;
            type_ = null;
            onChanged();
          }
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:PluginAdapter.Api.Configuration.Item)
      }

      // @@protoc_insertion_point(class_scope:PluginAdapter.Api.Configuration.Item)
      private static final PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item();
      }

      public static PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Item>
          PARSER = new com.google.protobuf.AbstractParser<Item>() {
        @java.lang.Override
        public Item parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Item(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Item> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Item> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    private java.util.List<PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item> items_;
    /**
     * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
     */
    public java.util.List<PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
     */
    public java.util.List<? extends PluginAdapter.Api.ConfigurationOuterClass.Configuration.ItemOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
     */
    public PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
     */
    public PluginAdapter.Api.ConfigurationOuterClass.Configuration.ItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PluginAdapter.Api.ConfigurationOuterClass.Configuration)) {
        return super.equals(obj);
      }
      PluginAdapter.Api.ConfigurationOuterClass.Configuration other = (PluginAdapter.Api.ConfigurationOuterClass.Configuration) obj;

      boolean result = true;
      result = result && getItemsList()
          .equals(other.getItemsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PluginAdapter.Api.ConfigurationOuterClass.Configuration parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PluginAdapter.Api.ConfigurationOuterClass.Configuration parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PluginAdapter.Api.ConfigurationOuterClass.Configuration parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PluginAdapter.Api.ConfigurationOuterClass.Configuration parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PluginAdapter.Api.ConfigurationOuterClass.Configuration parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PluginAdapter.Api.ConfigurationOuterClass.Configuration parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PluginAdapter.Api.ConfigurationOuterClass.Configuration parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PluginAdapter.Api.ConfigurationOuterClass.Configuration parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PluginAdapter.Api.ConfigurationOuterClass.Configuration parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PluginAdapter.Api.ConfigurationOuterClass.Configuration parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PluginAdapter.Api.ConfigurationOuterClass.Configuration parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PluginAdapter.Api.ConfigurationOuterClass.Configuration parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PluginAdapter.Api.ConfigurationOuterClass.Configuration prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Configurations contain a list of key-value pairs where each key identifies
     * something that can be configured and the value contains either the default
     * value (if the message comes from the adapter) or the current value (if the
     * message comes from TestManager).
     * </pre>
     *
     * Protobuf type {@code PluginAdapter.Api.Configuration}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PluginAdapter.Api.Configuration)
        PluginAdapter.Api.ConfigurationOuterClass.ConfigurationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PluginAdapter.Api.ConfigurationOuterClass.internal_static_PluginAdapter_Api_Configuration_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PluginAdapter.Api.ConfigurationOuterClass.internal_static_PluginAdapter_Api_Configuration_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PluginAdapter.Api.ConfigurationOuterClass.Configuration.class, PluginAdapter.Api.ConfigurationOuterClass.Configuration.Builder.class);
      }

      // Construct using PluginAdapter.Api.ConfigurationOuterClass.Configuration.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PluginAdapter.Api.ConfigurationOuterClass.internal_static_PluginAdapter_Api_Configuration_descriptor;
      }

      @java.lang.Override
      public PluginAdapter.Api.ConfigurationOuterClass.Configuration getDefaultInstanceForType() {
        return PluginAdapter.Api.ConfigurationOuterClass.Configuration.getDefaultInstance();
      }

      @java.lang.Override
      public PluginAdapter.Api.ConfigurationOuterClass.Configuration build() {
        PluginAdapter.Api.ConfigurationOuterClass.Configuration result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PluginAdapter.Api.ConfigurationOuterClass.Configuration buildPartial() {
        PluginAdapter.Api.ConfigurationOuterClass.Configuration result = new PluginAdapter.Api.ConfigurationOuterClass.Configuration(this);
        int from_bitField0_ = bitField0_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PluginAdapter.Api.ConfigurationOuterClass.Configuration) {
          return mergeFrom((PluginAdapter.Api.ConfigurationOuterClass.Configuration)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PluginAdapter.Api.ConfigurationOuterClass.Configuration other) {
        if (other == PluginAdapter.Api.ConfigurationOuterClass.Configuration.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PluginAdapter.Api.ConfigurationOuterClass.Configuration parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PluginAdapter.Api.ConfigurationOuterClass.Configuration) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = new java.util.ArrayList<PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item, PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item.Builder, PluginAdapter.Api.ConfigurationOuterClass.Configuration.ItemOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
       */
      public java.util.List<PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
       */
      public PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
       */
      public Builder setItems(
          int index, PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
       */
      public Builder setItems(
          int index, PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
       */
      public Builder addItems(PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
       */
      public Builder addItems(
          int index, PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
       */
      public Builder addItems(
          PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
       */
      public Builder addItems(
          int index, PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
       */
      public PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
       */
      public PluginAdapter.Api.ConfigurationOuterClass.Configuration.ItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
       */
      public java.util.List<? extends PluginAdapter.Api.ConfigurationOuterClass.Configuration.ItemOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
       */
      public PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
       */
      public PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .PluginAdapter.Api.Configuration.Item items = 1;</code>
       */
      public java.util.List<PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item, PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item.Builder, PluginAdapter.Api.ConfigurationOuterClass.Configuration.ItemOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item, PluginAdapter.Api.ConfigurationOuterClass.Configuration.Item.Builder, PluginAdapter.Api.ConfigurationOuterClass.Configuration.ItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PluginAdapter.Api.Configuration)
    }

    // @@protoc_insertion_point(class_scope:PluginAdapter.Api.Configuration)
    private static final PluginAdapter.Api.ConfigurationOuterClass.Configuration DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PluginAdapter.Api.ConfigurationOuterClass.Configuration();
    }

    public static PluginAdapter.Api.ConfigurationOuterClass.Configuration getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Configuration>
        PARSER = new com.google.protobuf.AbstractParser<Configuration>() {
      @java.lang.Override
      public Configuration parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Configuration(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Configuration> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Configuration> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PluginAdapter.Api.ConfigurationOuterClass.Configuration getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PluginAdapter_Api_Configuration_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PluginAdapter_Api_Configuration_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PluginAdapter_Api_Configuration_Item_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PluginAdapter_Api_Configuration_Item_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023configuration.proto\022\021PluginAdapter.Api" +
      "\"\300\001\n\rConfiguration\0224\n\005items\030\001 \003(\0132%.Plug" +
      "inAdapter.Api.Configuration.Item\032y\n\004Item" +
      "\022\013\n\003key\030\001 \001(\t\022\023\n\013description\030\002 \001(\t\022\020\n\006st" +
      "ring\030\003 \001(\tH\000\022\021\n\007integer\030\004 \001(\003H\000\022\017\n\005float" +
      "\030\005 \001(\002H\000\022\021\n\007boolean\030\006 \001(\010H\000B\006\n\004typeb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PluginAdapter_Api_Configuration_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PluginAdapter_Api_Configuration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PluginAdapter_Api_Configuration_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_PluginAdapter_Api_Configuration_Item_descriptor =
      internal_static_PluginAdapter_Api_Configuration_descriptor.getNestedTypes().get(0);
    internal_static_PluginAdapter_Api_Configuration_Item_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PluginAdapter_Api_Configuration_Item_descriptor,
        new java.lang.String[] { "Key", "Description", "String", "Integer", "Float", "Boolean", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
